//
// Created by VLAD on 11/19/2015.
//

#ifndef CARPOOLAPP_DISPLAYMESSAGEACTIVITY_H
#define CARPOOLAPP_DISPLAYMESSAGEACTIVITY_H


class DisplayMessageActivity {

};


#endif //CARPOOLAPP_DISPLAYMESSAGEACTIVITY_H
